number1=input('Enter number 1:')
number2=input('Enter number 2:')
print(number1,number2)
sum=int(number1)+int(number2)
print(sum)
difference=int(number1)-int(number2)
multiplication=int(number1)*int(number2)
division=int(number1)/int(number2)
print(difference,multiplication,division)
number3=input('Enter number 3:')
sum=int(number1)+int(number2)+int(number3)
difference=int(number1)-int(number2)-int(number3)
multiplication=int(number1)*int(number2)*int(number3)
division=int(number1)/int(number2)/int(number3)
print(difference,multiplication,division)
import math
print(math.pow(9,3))
print(math.sqrt(49))
print(math.cos(120))
print(math.exp(145))
print(math.isclose(13,18))
print(math.isfinite(132))
print(math.isinf(56))
print(math.perm(34))
print(math.log(54))
print(math.tan(65))
print(math.factorial(4))